#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/sync.h"
#include "Address.pio.h"    // Generated by pioasm
#include "Data.pio.h"       // Generated by pioasm
#include "sram.h"

#undef DEBUG

// loads main to static ram instead of non-volatile ram
//
//
//
//

int __not_in_flash_func(main)()
{
#ifdef DEBUG
    stdio_init_all();   // Initialize stdio (USB and UART if available)
#endif
    uint32_t status = save_and_disable_interrupts();            // disables the interrupts for this core

    /* Data bus 0 - 7 */
    PIO pioData = pio1;                                        // select one of two pios
    uint data_offset = pio_add_program(pioData, &Data_program);  // Load program
    uint sm2 = pio_claim_unused_sm(pioData, true);             // Claim a state machine

    Data_program_init(pioData, sm2, data_offset, 0);             // basepin = 0

    /* Adress buss 0 - n */
    PIO pio = pio0;                                     // select one of two pios
    uint address_offset = pio_add_program(pio, &Address_program); // Load program
    uint sm = pio_claim_unused_sm(pio, true);           // Claim a state machine

    // basepin = 8. Pins 8-20 (address), Pin 21 (RW), Pin 22 (Clock)
    Address_program_init(pio, sm, address_offset, 8);

    // Set up DMA for data output (Bus Read Cycle: SRAM -> PIO -> Bus)
    uint dma_chan_tx = dma_claim_unused_channel(true);
    dma_channel_config c_tx = dma_channel_get_default_config(dma_chan_tx);
    channel_config_set_transfer_data_size(&c_tx, DMA_SIZE_8);
    channel_config_set_read_increment(&c_tx, false);
    channel_config_set_write_increment(&c_tx, false);
    channel_config_set_dreq(&c_tx, pio_get_dreq(pioData, sm2, true)); // TX FIFO not full
    dma_channel_configure(dma_chan_tx, &c_tx, &pioData->txf[sm2], NULL, 1, false);

    // Set up DMA for data input (Bus Write Cycle: Bus -> PIO -> SRAM)
    uint dma_chan_rx = dma_claim_unused_channel(true);
    dma_channel_config c_rx = dma_channel_get_default_config(dma_chan_rx);
    channel_config_set_transfer_data_size(&c_rx, DMA_SIZE_8);
    channel_config_set_read_increment(&c_rx, false);
    channel_config_set_write_increment(&c_rx, false);
    channel_config_set_dreq(&c_rx, pio_get_dreq(pioData, sm2, false)); // RX FIFO not empty
    dma_channel_configure(dma_chan_rx, &c_rx, NULL, &pioData->rxf[sm2], 1, false);

    // The PIO program is now continuously reading the pins.
    // Your main loop can now read the values from the PIO FIFO.
    // This loop emulates an ROM.
    // bool RW_PIN = (address_raw >> 13) & 1;          // Bit 13 -> GPIO 21
    // bool CLK_PIN = (address_raw >> 14) & 1;         // Bit 14 -> GPIO 22
    
    while (true)
    {
        // Block until a new cycle is triggered by the PIO (GPIO 22 transition)
        register uint32_t address_raw = pio_sm_get_blocking(pio, sm);
        register uint32_t address = address_raw & 0x1FFF;        // Bits 0-12 (13 bits for 8KB)


        if ((address_raw >> 13) & 1)
        {
#ifdef DEBUG
            printf("Read: %02X address: %04X\n",sram[address],address);
#endif
            // Read Cycle: Set pins to output and send data from SRAM to the bus
            pio_sm_set_consecutive_pindirs(pioData, sm2, 0, 8, true);
            pio_sm_exec(pioData, sm2, pio_encode_jmp(data_offset + Data_offset_read_cycle));
            dma_channel_set_read_addr(dma_chan_tx, &sram[address], false);
            dma_channel_start(dma_chan_tx);
        }
        else
        {
            // Write Cycle: Set pins to input and capture data from the bus into SRAM
            pio_sm_set_consecutive_pindirs(pioData, sm2, 0, 8, false);
            pio_sm_exec(pioData, sm2, pio_encode_jmp(data_offset + Data_offset_write_cycle));
            dma_channel_set_write_addr(dma_chan_rx, &sram[address], false);
            dma_channel_start(dma_chan_rx);

            // Wait for DMA to finish before printing the updated SRAM value
            dma_channel_wait_for_finish_blocking(dma_chan_rx);
#ifdef DEBUG
            printf("Write: %02X address: %04X\n", sram[address], address);
#endif
        }
    }
}
