#include <stdio.h>
#include "pico/stdlib.h"
#include "pico/multicore.h"
#include "pico/time.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"    // for set_sys_clock_khz(250000, true)
#include "hardware/sync.h"
#include "Address.pio.h"    // Generated by pioasm
#include "sram.h"

void __not_in_flash_func(core1_entry)()
{
    gpio_put(PICO_DEFAULT_LED_PIN, 1);
    busy_wait_ms(500);

    volatile uint8_t *light = &sram[0x1c00];    // light points ta memory location voliatile makes sure it passes between cores
    while (true)
    {
        gpio_put(PICO_DEFAULT_LED_PIN, (*light) <= 127); // 0x55 must be set in 6502 assembler blink led
        tight_loop_contents();
    }
}

int __not_in_flash_func(main)()
{
    // 1. Increase clock speed to provide more overhead for the bus loop
    set_sys_clock_khz(250000, true);

    gpio_init(PICO_DEFAULT_LED_PIN);
    gpio_set_dir(PICO_DEFAULT_LED_PIN, GPIO_OUT);
    gpio_put(PICO_DEFAULT_LED_PIN, 0);
    busy_wait_ms(500);

    multicore_launch_core1(core1_entry);

    /* Initialize Data Bus (GPIO 0-7) for software (SIO) control */
    for (int i = 0; i < 8; i++)
    {
        gpio_init(i);
        gpio_set_dir(i, GPIO_IN);
        
        // 2. Set high drive strength and fast slew rate for the data bus
        // This ensures data is stable as quickly as possible during Read cycles
        gpio_set_drive_strength(i, GPIO_DRIVE_STRENGTH_12MA);
        gpio_set_slew_rate(i, GPIO_SLEW_RATE_FAST);
    }

    /* Address bus GPIO 8-22 plus GPIO 26 as A15, R/W GPIO 27, Clock GPIO 28 */
    PIO pio = pio0;                                     // select one of two pios
    uint address_offset = pio_add_program(pio, &Address_program); // Load program
    uint sm = pio_claim_unused_sm(pio, true);           // Claim a state machine
    Address_program_init(pio, sm, address_offset, 8, 27, 28);

    // Optimized pointers and masks for the tight loop
    const volatile uint32_t *pio_fifo = &pio->rxf[sm];
    const uint32_t data_mask = 0xFF;
    const uint32_t clock_pin_mask = (1u << 28);

    // stdio_init_all();   // Initialize stdio (USB and UART if available)
    
    // 3. Disable interrupts on this core. 
    // This prevents the USB stack or timers from causing jitter in the tight loop.
    uint32_t ints = save_and_disable_interrupts();

    // Pre-calculate masks to save cycles in the loop
    const uint32_t rw_mask = (1u << 27);

    while (true)
    {
        // Wait for a new address sample from the PIO
        while (pio_sm_is_rx_fifo_empty(pio, sm));

        uint32_t address_raw = *pio_fifo;
        uint32_t address = ((address_raw >> 8) & 0x7FFF) | ((address_raw & (1u << 26)) >> 11); // GPIO 8-22 plus GPIO 26 as A15

        if (address_raw & rw_mask)                    // GPIO 27 = R/W
        {
            // Read Cycle: SRAM -> Bus
            gpio_put_masked(data_mask, sram[address]);
            gpio_set_dir_out_masked(data_mask);
            
            // Wait for Clock (GPIO 28) to go low (end of cycle)
            while (sio_hw->gpio_in & clock_pin_mask);
            
            gpio_set_dir_in_masked(data_mask);

            // The PIO emits a second word every cycle: the last data sample
            // taken while PHI2 was high. Reads do not use it, but consuming it
            // keeps the FIFO stream aligned on the next address sample.
            while (pio_sm_is_rx_fifo_empty(pio, sm));
            (void)*pio_fifo;
//            printf("Read: %02X address: %04X\n",sram[address],address);
        }
        else
        {
            // Write Cycle: Bus -> SRAM
            // Use the last data sample captured by PIO while PHI2 was high.
            while (pio_sm_is_rx_fifo_empty(pio, sm));
            uint32_t data_raw = *pio_fifo;
            sram[address] = (uint8_t)(data_raw & data_mask);

//            printf("Write: %02X address: %04X\n", sram[address], address);
        }
    }
}
